### PR TITLE
feat: added flags for chapters

### LINKED ISSUE #53: make youtube chapters a flag
The timestamps have to be pretty exact for this to work, so I'd suggest we make this an optional flag so that we aren't splitting transcripts without the intention to do so.

### PR DESCRIPTION
**Pull request by masterchief164**
This PR fixes #53

### CODE REVIEW

**Comment by adamjonas** [comment]
The feature tests now take 64 times longer to complete. That's not going to work.

Screen Shot 2023-02-07 at 8 40 56 PM
Screen Shot 2023-02-07 at 8 40 52 PM


Additionally, you don't need a 9 min video to test these features. I don't think it's necessary to test whether whisper is transcribing audio in a test suite. Keep the feature tests to the features rather than testing the libraries.

**Comment by adamjonas** [comment]
Nice job speeding this up.

https://github.com/bitcointranscripts/tbtbtc/pull/62#issuecomment-1421820154 and specifically the comment about adding a 9 min video. I want to remove that 5MB asset from the repo if we don't need it. Don't you like a 15-second clip could accomplish the same thing as this full-length video?

**Comment by masterchief164** [comment]
> Nice job speeding this up.
> 
> [#62 (comment)](https://github.com/bitcointranscripts/tbtbtc/pull/62#issuecomment-1421820154) and specifically the comment about adding a 9 min video. I want to remove that 5MB asset from the repo if we don't need it. Don't you like a 15-second clip could accomplish the same thing as this full-length video?

I think a 15-second clip wont be able to have chapters in it.

**Comment by adamjonas** [comment]
🎉

**Pull request merged**
